version: '3.3'

services:
  postgres:
    image: postgres:13.5
    container_name: prisma_db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - 5432:5432