FROM nginx
COPY $PWD/config/p0ng.conf /etc/nginx/conf.d/default.conf
COPY $PWD/assets/Icons /usr/share/nginx/html/icons
COPY $PWD/assets/images /usr/share/nginx/html/images
COPY $PWD/assets/loop /usr/share/nginx/html/loop
